name: Build x86_64 LTO kernels

on:
  pull_request:
  create:
  workflow_call:

jobs:
  build:
    if: github.event_name != 'create'
    name: Build x86_64 LTO kernels
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make gcc clang lld llvm bc bison flex elfutils python3-pyelftools curl patch libelf-dev

      - name: Build x86_64 LTO packages
        run: make -f MakefileLto package

      - name: Upload x86_64 LTO workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: libkrunfw-x86_64-lto
          path: libkrunfw-x86_64-lto.tgz
          if-no-files-found: error

      - name: Upload x86_64 KVM LTO workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: libkrunfw-x86_64-kvm-lto
          path: libkrunfw-x86_64-kvm-lto.tgz
          if-no-files-found: error
